name: Bash Action

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Bash script
      run: |
        #!/bin/bash
        echo "Прізвище та ім'я: Artur Lopatniuk"
